FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    ansible \
    openssh-client \
    git \
    curl \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Ansible config
COPY ansible/ansible.cfg /etc/ansible/ansible.cfg

WORKDIR /ansible
